[Map,set] 3월 11일
Altu-Bitu-2/AltuBitu-Assignment pull request #2
Opened 2022-03-11 12:48 UTC by hyosin-Jang

#### 내용 & 질문
> 과제 제출합니다

#### <기존 제출>
> 2776, 9375, 11478, 19583, 20291, 20920

#### <추가 제출>
> X

2022-03-12 16:13 UTC, mkwkw requested changes
맵과 셋을 이용해서 전체적으로 잘 풀어주셨습니다! 6문제 다 정답이므로 쿠폰도 하나 적립해드렸어요.

전체적으로 주석이 너무 없습니다! 주석은 본인의 코드 이해 및 작성, 타인이 코드 이해에도 도움이 됩니다~ 꼭 작성해주세요:)

p2 부분 수정해주시고 오른쪽 상단의 re-request review 버튼 눌러주세요~
p3 부분은 한번 생각해보시면 도움이 될 것 같아요~!

2022-03-12 16:13 UTC, mkwkw commented on 03월 08일 - 맵과 셋/19583.cpp
> +}
p3. set을 이용해서 깔끔하게 잘 풀어주셨습니다! 이 문제는 set으로도 풀 수 있고 map으로도 풀 수 있어요~ map으로도 푸는 방법을 한번 생각해보시는 것도 좋을 것 같아요:)

2022-03-12 16:13 UTC, mkwkw commented on 03월 08일 - 맵과 셋/20291.cpp
> +}
p2. map으로 잘 풀어주셨지만 split함수를 따로 정의하지 않고 find함수만 잘 활용한다면 코드를 조금 더 간결하게 작성할 수 있어요! find 함수를 쓰는 방향을 생각해보시길 바랄게요:)

2022-03-15 07:25 UTC, hyosin-Jang commented on 03월 08일 - 맵과 셋/20291.cpp
> +}
find 쓰니까 훨씬 간결하네요..! split 대신 find 함수로 수정했습니다!

2022-03-16 04:38 UTC, mkwkw approved these changes
확인했습니다. 머지하셔도 됩니다~

2022-03-16 07:16 UTC, merged